name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jayzau/NoteBook@master
      env:
        ACCESS_TOKEN: ${{ secrets.GIO }}
        TARGET_REPO: jayzau/jayzau.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: https://www.xxx.com